I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 85, in script
    show K at left2 with dissolve
  File "game/script.rpy", line 85, in <module>
    show K at left2 with dissolve
NameError: name 'left2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 85, in script
    show K at left2 with dissolve
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 85, in <module>
    show K at left2 with dissolve
NameError: name 'left2' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Final Abdul 0.1.3.1
Wed Mar  6 19:28:41 2024
